services:
  postgres:
    image: banhmysuawx/postgres-pgbigm:15-alpine
    container_name: postgres
    env_file: .env
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d
    command: ["postgres", "-c", "shared_preload_libraries=pg_trgm,pg_bigm,pgcrypto"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - data_net

volumes:
  postgres_data:

networks:
  data_net:
    driver: bridge