"""Initial revision

Revision ID: 5db8dd1383b0
Revises: 
Create Date: 2024-12-10 22:29:43.725385

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5db8dd1383b0"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cars",
        sa.Column("car_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("car_number", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("car_id"),
        sa.UniqueConstraint("car_number"),
    )
    op.create_table(
        "users",
        sa.Column("user_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("firstname", sa.String(), nullable=False),
        sa.Column("lastname", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("password_hash", sa.String(), nullable=False),
        sa.Column("phone_number", sa.String(), nullable=False),
        sa.Column("role", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("user_id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("password_hash"),
        sa.UniqueConstraint("phone_number"),
    )
    op.create_table(
        "analysts",
        sa.Column(
            "analyst_id", sa.Integer(), autoincrement=True, nullable=False
        ),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("grade", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.user_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("analyst_id"),
    )
    op.create_table(
        "car_info",
        sa.Column("car_id", sa.Integer(), nullable=False),
        sa.Column("color", sa.String(), nullable=False),
        sa.Column("model", sa.String(), nullable=False),
        sa.Column("car_class", sa.String(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["car_id"], ["cars.car_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("car_id"),
    )
    op.create_table(
        "drivers",
        sa.Column(
            "driver_id", sa.Integer(), autoincrement=True, nullable=False
        ),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("birth_date", sa.DATE(), nullable=False),
        sa.Column("sex", sa.String(), nullable=False),
        sa.Column("driver_rides", sa.Integer(), nullable=False),
        sa.Column("driver_time_accidents", sa.Integer(), nullable=False),
        sa.Column("driver_license_number", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.user_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("driver_id"),
        sa.UniqueConstraint("driver_license_number"),
    )
    op.create_table(
        "passengers",
        sa.Column(
            "passenger_id", sa.Integer(), autoincrement=True, nullable=False
        ),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("birth_date", sa.DATE(), nullable=False),
        sa.Column("sex", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.user_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("passenger_id"),
    )
    op.create_table(
        "rides",
        sa.Column("ride_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("driver_id", sa.Integer(), nullable=False),
        sa.Column("passenger_id", sa.Integer(), nullable=False),
        sa.Column("car_id", sa.Integer(), nullable=False),
        sa.Column("rate", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["car_id"],
            ["cars.car_id"],
        ),
        sa.ForeignKeyConstraint(
            ["driver_id"],
            ["drivers.driver_id"],
        ),
        sa.ForeignKeyConstraint(
            ["passenger_id"],
            ["passengers.passenger_id"],
        ),
        sa.PrimaryKeyConstraint("ride_id"),
    )
    op.create_table(
        "ride_info",
        sa.Column("ride_id", sa.Integer(), nullable=False),
        sa.Column("ride_date", sa.DateTime(), nullable=False),
        sa.Column("ride_duration_seconds", sa.Integer(), nullable=False),
        sa.Column("ride_cost_rubles", sa.Integer(), nullable=False),
        sa.Column("distance", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["ride_id"], ["rides.ride_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("ride_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("ride_info")
    op.drop_table("rides")
    op.drop_table("passengers")
    op.drop_table("drivers")
    op.drop_table("car_info")
    op.drop_table("analysts")
    op.drop_table("users")
    op.drop_table("cars")
    # ### end Alembic commands ###
